# core/nodes/SafetyGuardrailNode.py
"""
Safety Guardrail Node (Layer 0 — Hard Safety Gate)

This node sits BEFORE everything else in the flow.
It classifies user input as SAFE, WARN, or BLOCK.

- SAFE  → Continue to ClinicalStateManager (normal flow)
- WARN  → Continue BUT flag the conversation for monitoring
- BLOCK → Immediately return safety response, skip ALL medical logic
"""

from pocketflow import Node
import logging

from utils.llm import call_llm
from utils.llm.prompts_advanced import SAFETY_GUARDRAIL_PROMPT
from utils.parsing.response_parser import parse_json_from_llm
from config.timeout_config import timeout_config

# Configure logging
from utils.timezone_utils import setup_vietnam_logging
from config.logging_config import logging_config

if logging_config.USE_VIETNAM_TIMEZONE:
    logger = setup_vietnam_logging(__name__,
                                 level=getattr(logging, logging_config.LOG_LEVEL.upper()),
                                 format_str=logging_config.LOG_FORMAT)
else:
    logger = logging.getLogger(__name__)
    logger.setLevel(getattr(logging, logging_config.LOG_LEVEL.upper()))


# ============================================================================
# Hardcoded safety responses (NOT generated by LLM)
# ============================================================================

BLOCK_RESPONSE_SELF_HARM = (
    "🚨 **Chúng tôi nhận thấy bạn có thể đang gặp khó khăn.**\n\n"
    "Hệ thống AI y tế không thể hỗ trợ yêu cầu này. "
    "Nếu bạn hoặc người thân đang trong tình trạng khẩn cấp, "
    "vui lòng liên hệ ngay:\n\n"
    "📞 **Đường dây nóng hỗ trợ tâm lý:** `1800 599 100` (miễn phí, 24/7)\n"
    "📞 **Cấp cứu:** `115`\n"
    "📞 **Tổng đài tư vấn sức khỏe tâm thần:** `1900 0027`\n\n"
    "⚠️ Bạn không cô đơn. Hãy gọi ngay để được hỗ trợ."
)

BLOCK_RESPONSE_HARM_OTHERS = (
    "🚫 **Yêu cầu bị từ chối.**\n\n"
    "Hệ thống AI y tế **không cung cấp** thông tin có thể "
    "được sử dụng để gây hại cho người khác.\n\n"
    "Nếu bạn hoặc ai đó đang gặp nguy hiểm, "
    "vui lòng gọi **Công an: `113`** hoặc **Cấp cứu: `115`** ngay lập tức."
)

BLOCK_RESPONSE_POISON = (
    "🚫 **Yêu cầu bị từ chối.**\n\n"
    "Hệ thống AI y tế **không cung cấp** hướng dẫn chế tạo "
    "chất độc, chất cấm, hoặc bất kỳ chất nào có thể gây hại.\n\n"
    "Nếu bạn bị ngộ độc hoặc nghi ngờ ngộ độc, "
    "hãy gọi **Cấp cứu: `115`** hoặc đến cơ sở y tế gần nhất."
)

BLOCK_RESPONSE_DRUG_ABUSE = (
    "🚫 **Yêu cầu bị từ chối.**\n\n"
    "Hệ thống AI y tế **không hỗ trợ** việc lạm dụng thuốc "
    "hoặc sử dụng thuốc trái phép.\n\n"
    "Nếu bạn cần hỗ trợ về vấn đề nghiện chất, "
    "vui lòng liên hệ **Đường dây nóng: `1800 599 100`** "
    "hoặc đến cơ sở cai nghiện gần nhất."
)

BLOCK_RESPONSES = {
    "self_harm": BLOCK_RESPONSE_SELF_HARM,
    "harm_others": BLOCK_RESPONSE_HARM_OTHERS,
    "poison_creation": BLOCK_RESPONSE_POISON,
    "drug_abuse": BLOCK_RESPONSE_DRUG_ABUSE,
}

BLOCK_RESPONSE_DEFAULT = (
    "🚫 **Yêu cầu bị từ chối.**\n\n"
    "Hệ thống AI y tế không thể hỗ trợ yêu cầu này vì lý do an toàn.\n\n"
    "Nếu bạn cần hỗ trợ y tế khẩn cấp, hãy gọi **Cấp cứu: `115`**."
)


class SafetyGuardrailNode(Node):
    """
    Layer 0: Hard Safety Gate.

    Classifies user input and either allows it through (SAFE/WARN)
    or blocks it entirely (BLOCK) with a hardcoded safety response.
    """

    def __init__(self, max_retries=1, wait=0):
        super().__init__(max_retries=max_retries, wait=wait)

    def prep(self, shared):
        query = shared.get("input", shared.get("query", ""))
        logger.info(f"🛡️ [SafetyGuardrail] PREP - Checking input: '{query[:80]}...'")
        return {"query": query}

    def exec(self, inputs):
        query = inputs["query"]

        if not query or not query.strip():
            return {"classification": "SAFE", "reason": "Empty input", "threat_type": "none"}

        # Call LLM to classify the input
        prompt = SAFETY_GUARDRAIL_PROMPT.format(user_input=query)

        try:
            response_str = call_llm(prompt, max_retry_time=timeout_config.LLM_RETRY_TIMEOUT)
            result = parse_json_from_llm(response_str)

            if not result or not isinstance(result, dict):
                logger.warning("🛡️ [SafetyGuardrail] EXEC - Could not parse LLM response, defaulting to SAFE")
                return {"classification": "SAFE", "reason": "Parse error", "threat_type": "none"}

            classification = result.get("classification", "SAFE").upper()
            reason = result.get("reason", "")
            threat_type = result.get("threat_type", "none")

            # Validate classification
            if classification not in {"SAFE", "WARN", "BLOCK"}:
                classification = "SAFE"

            logger.info(f"🛡️ [SafetyGuardrail] EXEC - Classification: {classification} | Threat: {threat_type} | Reason: {reason}")
            return {
                "classification": classification,
                "reason": reason,
                "threat_type": threat_type,
            }

        except Exception as e:
            logger.error(f"🛡️ [SafetyGuardrail] EXEC - Error during safety check: {e}")
            # On error, default to SAFE to avoid blocking legitimate queries
            return {"classification": "SAFE", "reason": f"Error: {str(e)}", "threat_type": "none"}

    def post(self, shared, prep_res, exec_res):
        if exec_res is None:
            logger.error("🛡️ [SafetyGuardrail] POST - exec_res is None, allowing through")
            return "safe"

        classification = exec_res.get("classification", "SAFE")
        threat_type = exec_res.get("threat_type", "none")
        reason = exec_res.get("reason", "")

        # Store safety metadata in shared for downstream nodes
        shared["safety_classification"] = classification
        shared["safety_threat_type"] = threat_type
        shared["safety_reason"] = reason

        if classification == "BLOCK":
            # HARD BLOCK: Set the answer directly and skip the entire pipeline
            block_response = BLOCK_RESPONSES.get(threat_type, BLOCK_RESPONSE_DEFAULT)

            shared["answer_obj"] = {
                "explanation": block_response,
                "suggestion_questions": [
                    "Tôi muốn hỏi về triệu chứng bệnh",
                    "Tôi cần tư vấn về thuốc điều trị",
                    "Tôi cần thông tin về chế độ dinh dưỡng",
                ],
            }
            shared["explain"] = block_response
            shared["suggestion_questions"] = shared["answer_obj"]["suggestion_questions"]

            logger.warning(f"🛡️ [SafetyGuardrail] POST - ⛔ BLOCKED: {reason} (threat={threat_type})")
            return "blocked"

        elif classification == "WARN":
            logger.warning(f"🛡️ [SafetyGuardrail] POST - ⚠️ WARN: {reason} (threat={threat_type})")
            return "safe"  # Allow through but logged

        else:
            logger.info(f"🛡️ [SafetyGuardrail] POST - ✅ SAFE: {reason}")
            return "safe"
